#!/usr/bin/python

import urllib.parse, urllib.request
import local_updates

def pull_from_zoltan():
    request = urllib.request.Request('http://zoltan/vpn_ip.txt')
    with urllib.request.urlopen(request) as response:
        ip = response.read().decode('utf-8').strip()
        print('vpn ip reported by zoltan is: {}'.format(ip))
        local_updates.vpn_ip_changed(ip)

if __name__ == '__main__':
    pull_from_zoltan()
