#!/usr/bin/python

from xmlrpc.server import SimpleXMLRPCServer
from xmlrpc.server import SimpleXMLRPCRequestHandler
import local_updates

listen_ip = '0.0.0.0'
listen_port = 8000

# call the worker function
def update_vpn_ip(local_ip):
    print('received notice of ip address change: {}'.format(local_ip))
    try:
        local_updates.vpn_ip_changed(local_ip)
    except Exception as e:
        # catch everything and keep going
        print('ERROR: {}'.format(e))

# Restrict to a particular path.
class RequestHandler(SimpleXMLRPCRequestHandler):
    rpc_paths = ('/RPC2',)

# Create server
server = SimpleXMLRPCServer((listen_ip, listen_port),
                            requestHandler=RequestHandler,
                            allow_none=True,
                            logRequests=False)
server.register_introspection_functions()
server.register_function(update_vpn_ip)
print('starting XML RPC server on {}:{}'.format(listen_ip, listen_port))
server.serve_forever()

