#!/usr/local/bin/python2.7

from __future__ import print_function
try:
    from xmlrpclib import ServerProxy
except:
    from xmlrpc.client import ServerProxy
import sys
import os

def send_update():
    s = ServerProxy('http://varch:8000')
    try:
        s.update_vpn_ip(sys.argv[1])
    except Exception as e:
        print('ERROR: %' % e)

if __name__ == '__main__':
    try:
        pid = os.fork()
        if pid > 0:
            sys.exit(0)
    except OSError as e:
        print('fork failed: %d (%s)' % (e.errno, e.strerror), file=sys.stderr)
        sys.exit(1)

    os.chdir('/')
    os.setsid()
    os.umask(0)

    send_update()

