#!/usr/bin/python -u

from xmlrpc.server import SimpleXMLRPCServer
from xmlrpc.server import SimpleXMLRPCRequestHandler
from argparse import ArgumentParser
import local_updates
import os
import sys
import logging, logging.handlers

config = None

# call the worker function
def update_vpn_port(port):
    global config
    logging.info('received notice of forwarded port change: {}'.format(port))
    try:
        local_updates.vpn_port_changed(port, config.config_dir)
    except Exception as e:
        # catch everything and keep going
        logging.error(e)

# Restrict to a particular path.
class RequestHandler(SimpleXMLRPCRequestHandler):
    rpc_paths = ('/RPC2',)

def serve_it(listen_ip, listen_port):
    """Create server and serve!"""
    server = SimpleXMLRPCServer((listen_ip, listen_port),
                                requestHandler=RequestHandler,
                                allow_none=True,
                                logRequests=False)
    server.register_introspection_functions()
    server.register_function(update_vpn_port)
    logging.info('starting XML RPC server on {}:{}'.format(listen_ip, listen_port))
    try:
        server.serve_forever()
    except Exception as e:
        logging.critical('received exception: {}'.format(e))
        logging.info('exiting')
        sys.exit(1)

if __name__ == '__main__':
    parser = ArgumentParser(description='XMLRPC server to set deluge port')
    parser.add_argument('--listen-ip',   '-l', metavar='IP', type=str, default='0.0.0.0', help='IP address to listen on (default 0.0.0.0)')
    parser.add_argument('--listen-port', '-p', metavar='PORT', type=int, default=8108, help='IP port to listen on (default 8108)')
    parser.add_argument('--config-dir',  '-c', metavar='DIR', type=str, default='/config', help='Deluge config directory (default "/config")')
    parser.add_argument('--logging',     '-L', metavar='FILE_OR_SYSLOG', default='stderr', help='Send logging info to given file or to "syslog" (default stderr)')
    config = parser.parse_args()
    if config.logging in ['stderr', 'syslog']:
        logging.basicConfig(format='%(asctime)s %(module)s %(levelname)s %(message)s', level=logging.INFO)
        if config.logging == 'syslog':
            log_address=('localhost', 514)
            if os.path.exists('/dev/log'):
                log_address='/dev/log'
            logging.getLogger().addHandler(logging.handlers.SysLogHandler(address=log_address))
    else:
        logging.basicConfig(filename=config.logging, format='%(asctime)s %(module)s %(levelname)s %(message)s', level=logging.INFO)
    serve_it(config.listen_ip, config.listen_port)

